### ISSUE TITLE
xtf namespace prefix missing in ;raw=1 display

### ISSUE THREAD

**Issue by sdm7g** [cdlib/xtf#9]
There's been a longstanding and annoying issue that viewing XML files with ";raw=1" yields an error in the browser due to missing xtf namespace prefix. I recently noticed this:

    /** Determines whether this document is using namespaces. Not sure why
      *  this works when false, but it does.
      */
    protected boolean usesNamespaces = false;

https://github.com/cdlib/xtf/blob/master/WEB-INF/src/org/cdlib/xtf/lazyTree/LazyDocument.java#L61-L64

It turns out that changing the above  to `true`  causes raw output to include those namespace prefixes and work properly.  

_( Doing further testing before submitting a pull req to see if there are any other side effects of this change. )_

**Comment by martinhaye** [comment]
Thanks for the fix! So great.
